# Generated by Django 4.0.3 on 2022-05-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_add_user', "Yangi foydalanuuvchi qo'shish")]},
        ),
    ]
