# Generated by Django 4.0.3 on 2022-04-29 06:18

import courses.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Kommentariya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
            ],
            options={
                'verbose_name': 'Komentariya',
                'verbose_name_plural': 'Komentariyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Dars nomerini korsating', verbose_name='Nomer')),
                ('title', models.CharField(max_length=255, verbose_name='Tema')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('script', models.TextField(blank=True, verbose_name='Script')),
                ('video', models.FileField(upload_to=courses.utils.save_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Video')),
                ('materials', models.FileField(blank=True, upload_to=courses.utils.save_materials, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Materiallar')),
                ('homework', models.FileField(blank=True, upload_to=courses.utils.save_homework, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Uy ishi')),
                ('additional_materials', models.FileField(blank=True, upload_to=courses.utils.save_additional_materials, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Qoshimcha material')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ozgartirilgan vaqti')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yuklash')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_lessons', 'Barcha darslarni korish'), ('can_view_lessons_by_course', 'Faqat kursni korish'), ('can_add_lesson', 'Dars qoshish'), ('can_update_lesson', 'Darsni ozgartirish'), ('can_delete_lesson', 'Darsni ochirish')],
            },
        ),
    ]
